select ai.ANIMAL_ID as ANIMAL_ID, ai.ANIMAL_TYPE as ANIMAL_TYPE, ai.NAME as NAME
from ANIMAL_INS ai
inner join ANIMAL_OUTS ao
on ai.ANIMAL_ID = ao.ANIMAL_ID
where ai.SEX_UPON_INTAKE != ao.SEX_UPON_OUTCOME;