select CAR_ID, ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1), 1) as AVERAGE_DURATION
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID
having AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1) >= 7
order by AVERAGE_DURATION desc, CAR_ID desc;