WITH C1 AS (
    SELECT MAX(fp.PRICE) as MAX_PRICE
    FROM FOOD_PRODUCT fp
)

SELECT fp.PRODUCT_ID as PRODUCT_ID,
        fp.PRODUCT_NAME as PRODUCT_NAME,
        fp.PRODUCT_CD as PRODUCT_CD,
        fp.CATEGORY as CATEGORY,
        fp.PRICE as PRICE
FROM FOOD_PRODUCT fp
JOIN C1 c1
ON fp.PRICE = c1.MAX_PRICE;