SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') AND PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT AS F WHERE F.CATEGORY = FOOD_PRODUCT.CATEGORY)
GROUP BY CATEGORY, PRODUCT_NAME
ORDER BY MAX_PRICE DESC;